<?php

return [

    'telephone_codes' => [
        ["name" => 'UK (+44)', "code" => '44'],
        ["name" => 'USA (+1)', "code" => '1'],
        ["name" => 'Algeria (+213)', "code" => '213'],
        ["name" => 'Andorra (+376)', "code" => '376'],
        ["name" => 'Angola (+244)', "code" => '244'],
        ["name" => 'Anguilla (+1264)', "code" => '1264'],
        ["name" => 'Antigua & Barbuda (+1268)', "code" => '1268'],
        ["name" => 'Argentina (+54)', "code" => '54'],
        ["name" => 'Armenia (+374)', "code" => '374'],
        ["name" => 'Aruba (+297)', "code" => '297'],
        ["name" => 'Australia (+61)', "code" => '61'],
        ["name" => 'Austria (+43)', "code" => '43'],
        ["name" => 'Azerbaijan (+994)', "code" => '994'],
        ["name" => 'Bahamas (+1242)', "code" => '1242'],
        ["name" => 'Bahrain (+973)', "code" => '973'],
        ["name" => 'Bangladesh (+880)', "code" => '880'],
        ["name" => 'Barbados (+1246)', "code" => '1246'],
        ["name" => 'Belarus (+375)', "code" => '375'],
        ["name" => 'Belgium (+32)', "code" => '32'],
        ["name" => 'Belize (+501)', "code" => '501'],
        ["name" => 'Benin (+229)', "code" => '229'],
        ["name" => 'Bermuda (+1441)', "code" => '1441'],
        ["name" => 'Bhutan (+975)', "code" => '975'],
        ["name" => 'Bolivia (+591)', "code" => '591'],
        ["name" => 'Bosnia Herzegovina (+387)', "code" => '387'],
        ["name" => 'Botswana (+267)', "code" => '267'],
        ["name" => 'Brazil (+55)', "code" => '55'],
        ["name" => 'Brunei (+673)', "code" => '673'],
        ["name" => 'Bulgaria (+359)', "code" => '359'],
        ["name" => 'Burkina Faso (+226)', "code" => '226'],
        ["name" => 'Burundi (+257)', "code" => '257'],
        // … (KEEP THE REST SAME)
    ],

    'time_zone' => [
        "Pacific/Midway",
        "Pacific/Samoa",
        "Pacific/Honolulu",
        "US/Alaska",
        "America/Los_Angeles",
        "America/Tijuana",
        "US/Arizona",
        "America/Chihuahua",
        "America/Mazatlan",
        "US/Mountain",
        "America/Managua",
        "US/Central",
        "America/Mexico_City",
        "America/Monterrey",
        "Canada/Saskatchewan",
        "America/Bogota",
        "US/Eastern",
        "America/Lima",
        // … (KEEP THE REST SAME)
    ],

    'module_permission' => [
        "dashboard_section",
        "pos_section",
        "product_section",
        "employee_section",
        "employee_role_section",
        "customer_section",
        "supplier_section",
        "setting_section",
        "category_section",
        "brand_section",
        "unit_section",
        "account_section",
        "stock_section",
        "coupon_section",
    ],

];
